# Funding channels for discretus.
#
# The project is developed at the School of ICT, Metropolia University of
# Applied Sciences and does not currently accept individual sponsorship.
# Institutional collaboration enquiries go to the corresponding author.

github: [olaflaitinen]
custom: ["https://github.com/olaflaitinen/discretus"]
