#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Generate type stubs for the library, and audit the annotations behind them.

Why this script exists
======================

The library is annotated inline and ships a ``py.typed`` marker, so a type
checker reads the annotations straight out of the source and no stub file is
needed to use it. That is the right arrangement: one copy of every signature,
in the file that implements it, where it cannot fall behind.

Two things still want stubs, and both are why this script exists.

The first is tooling that cannot read inline annotations. Some editors, some
older checkers, and some build systems consume a stub tree and nothing else.
Generating one on demand serves them without adding a second copy of every
signature to the repository, which is the thing worth avoiding.

The second, and the more useful in practice, is the audit. Producing a stub
means walking every public signature and writing down its annotations, which
is exactly the walk needed to answer whether any of them are missing. A
parameter with no annotation and a routine with no return annotation are both
invisible in normal use and both defeat the purpose of shipping a typed
package, so the check mode reports them.

How the stubs are produced
==========================

By parsing the source, not by importing it. Two reasons:

Importing executes module level code, which for a partially built library
means the generation depends on which packages happen to be implemented. A
parse works on any file that is syntactically valid, including one whose
dependencies are not written yet.

An imported object has lost the source form of its annotations. A default of
``()`` becomes an empty tuple, a string annotation stays a string, and a
union written with a vertical bar has already been evaluated. The parse keeps
what the author wrote, which is what a stub is supposed to record.

The mypy stub generator is used instead when --use-stubgen is given, for a
cross check: two independent renderings of the same signatures that disagree
mean one of them is wrong, and that is worth knowing.

What is emitted
===============

For every module, a stub carrying the license notice, the module's own import
statements verbatim, then its public classes and functions with their
signatures and no bodies. A docstring is dropped, because a stub is read by a
checker rather than by a person, and the reference is generated from the
source. A private name is dropped unless --include-private is given.

Usage
=====

    scripts/generate_stubs.py                     write to build/stubs
    scripts/generate_stubs.py --output tmp/stubs
    scripts/generate_stubs.py --check             audit only, write nothing
    scripts/generate_stubs.py --diff              compare against the output
    scripts/generate_stubs.py --print discretus.core.element
    scripts/generate_stubs.py --use-stubgen       delegate to mypy

Exit status
===========

    0   the stubs were written, or the audit found nothing
    1   the audit found a missing annotation, or a comparison differed
    2   the command line was wrong, or a requested tool is absent
"""

from __future__ import annotations

import argparse
import ast
import pathlib
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

# ---------------------------------------------------------------------------
# Locations
# ---------------------------------------------------------------------------

#: The repository root, derived from this file so that the script behaves the
#: same however it is invoked.
REPOSITORY_ROOT = pathlib.Path(__file__).resolve().parents[1]

#: The package to generate stubs for.
PACKAGE_ROOT = REPOSITORY_ROOT / "discretus"

#: Where the stub tree is written by default. Inside the build directory,
#: which .gitignore excludes, because a generated tree does not belong in the
#: repository: it would be a second copy of every signature, free to drift.
DEFAULT_OUTPUT = REPOSITORY_ROOT / "build" / "stubs"

#: The notice every generated file carries. The license applies per file, so
#: a generated file needs it as much as a written one.
LICENSE_NOTICE = """# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""

#: The line that says a stub was generated, so that nobody edits one by hand
#: and expects the edit to survive.
GENERATED_MARKER = (
    "# Generated by scripts/generate_stubs.py. Do not edit.\n"
    "# The annotations live in the source; this file is derived from them.\n"
)

#: Special methods whose signature a checker already knows and whose absence
#: from a stub changes nothing. They are emitted anyway, because a subclass
#: may narrow one, and listing them here documents that the choice was made.
ALWAYS_EMIT_SPECIAL = (
    "__init__",
    "__new__",
    "__call__",
    "__enter__",
    "__exit__",
    "__iter__",
    "__next__",
    "__len__",
    "__contains__",
    "__getitem__",
    "__eq__",
    "__lt__",
    "__le__",
    "__gt__",
    "__ge__",
    "__hash__",
    "__repr__",
    "__str__",
    "__bool__",
    "__add__",
    "__mul__",
    "__sub__",
    "__or__",
    "__and__",
    "__xor__",
)


# ---------------------------------------------------------------------------
# Findings
# ---------------------------------------------------------------------------


@dataclass
class Finding:
    """One annotation defect found while walking the source.

    Attributes:
        path: The file it was found in, relative to the repository root.
        line: The line the definition starts on.
        name: The qualified name of the definition.
        problem: What is missing, phrased as the remedy.
    """

    path: str
    line: int
    name: str
    problem: str

    def render(self) -> str:
        """Return the finding as one line, in the usual compiler form."""
        return f"{self.path}:{self.line}: {self.name}: {self.problem}"


@dataclass
class ModuleStub:
    """The stub text for one module, with the findings from producing it.

    Attributes:
        source: The source file the stub was produced from.
        target: Where the stub file goes, relative to the output directory.
        text: The stub source.
        findings: The annotation defects noticed along the way.
        emitted: How many definitions the stub carries.
    """

    source: pathlib.Path
    target: pathlib.Path
    text: str
    findings: List[Finding] = field(default_factory=list)
    emitted: int = 0


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def unparse(node: Optional[ast.AST]) -> str:
    """Return the source form of a node, or the empty string for nothing.

    Args:
        node: The node to render, or None.

    Returns:
        The rendered source.

    Examples:
        >>> unparse(ast.parse("x: int", mode="exec").body[0].annotation)
        'int'
        >>> unparse(None)
        ''
    """
    if node is None:
        return ""
    return ast.unparse(node)


def is_private(name: str) -> bool:
    """Return whether a name is private by the leading underscore rule.

    A special method is not private, because it is part of the interface
    even though its name begins with underscores.

    Examples:
        >>> is_private("_helper")
        True
        >>> is_private("__init__")
        False
        >>> is_private("value")
        False
    """
    if name.startswith("__") and name.endswith("__"):
        return False
    return name.startswith("_")


def decorator_names(node: ast.AST) -> List[str]:
    """Return the decorator names of a definition, without their arguments.

    Args:
        node: A class or function definition.

    Returns:
        The rendered decorators, in source order.
    """
    decorators = getattr(node, "decorator_list", [])
    return [unparse(decorator) for decorator in decorators]


def render_signature(node: ast.AST) -> str:
    """Return the parameter list of a function, as written in the source.

    The whole argument node is rendered, which keeps the positional only and
    keyword only markers, the star arguments, and the defaults in the form
    the author wrote them.

    Args:
        node: A function definition.

    Returns:
        The rendered parameters, without the surrounding parentheses.
    """
    return unparse(node.args)


def annotation_findings(
    node: ast.AST, qualified: str, path: str, in_class: bool
) -> List[Finding]:
    """Return the missing annotations of one function.

    The rules match what a typed package has to provide to be useful:

    Every parameter needs an annotation, except ``self`` in a method and
    ``cls`` in a class method, which a checker infers.

    Every routine needs a return annotation, including one that returns
    nothing, because the absence of an annotation and an annotation of None
    mean different things to a checker.

    Args:
        node: A function definition.
        qualified: The name to report the finding under.
        path: The file the definition is in.
        in_class: Whether the definition is a method.

    Returns:
        One finding per missing annotation.
    """
    findings: List[Finding] = []
    arguments = node.args

    positional = list(getattr(arguments, "posonlyargs", [])) + list(arguments.args)
    implicit = {"self", "cls"} if in_class else set()

    for index, argument in enumerate(positional):
        if index == 0 and in_class and argument.arg in implicit:
            continue
        if argument.annotation is None:
            findings.append(
                Finding(
                    path, node.lineno, qualified, f"{argument.arg} has no annotation"
                )
            )

    for argument in arguments.kwonlyargs:
        if argument.annotation is None:
            findings.append(
                Finding(
                    path, node.lineno, qualified, f"{argument.arg} has no annotation"
                )
            )

    for special in (arguments.vararg, arguments.kwarg):
        if special is not None and special.annotation is None:
            findings.append(
                Finding(
                    path, node.lineno, qualified, f"{special.arg} has no annotation"
                )
            )

    if node.returns is None:
        findings.append(
            Finding(path, node.lineno, qualified, "has no return annotation")
        )

    return findings


# ---------------------------------------------------------------------------
# The generator
# ---------------------------------------------------------------------------


class StubGenerator:
    """Produce a stub for one module by walking its syntax tree.

    The generator is deliberately literal. It copies the import statements,
    renders the definitions with their annotations as written, and drops
    everything a checker does not read, namely the bodies, the docstrings,
    and the private names. It does not try to infer a type that the source
    does not state: an unannotated parameter becomes a finding rather than a
    guess, because a guess in a stub is worse than an omission.

    Attributes:
        include_private: Whether to emit names with a leading underscore.
    """

    def __init__(self, include_private: bool = False) -> None:
        """Prepare a generator.

        Args:
            include_private: Whether to emit private names.
        """
        self.include_private = include_private

    # -- module level -----------------------------------------------------

    def generate(self, source: pathlib.Path) -> ModuleStub:
        """Return the stub for one source file.

        Args:
            source: The module to read.

        Returns:
            The stub, with its findings and its definition count.
        """
        relative = source.relative_to(REPOSITORY_ROOT)
        target = relative.with_suffix(".pyi")
        text = source.read_text(encoding="utf-8")

        if not text.strip():
            # An empty placeholder for a package that is not written yet.
            # A stub for it is an empty stub, which is correct and keeps the
            # tree shaped like the package.
            return ModuleStub(source, target, LICENSE_NOTICE + GENERATED_MARKER)

        tree = ast.parse(text, filename=str(source))
        stub = ModuleStub(source, target, "")

        lines: List[str] = [LICENSE_NOTICE, GENERATED_MARKER, "\n"]

        imports = self.render_imports(tree)
        if imports:
            lines.extend(imports)
            lines.append("\n")

        exported = self.render_exports(tree)
        if exported:
            lines.extend(exported)
            lines.append("\n")

        body = self.render_body(tree, str(relative), stub)
        lines.extend(body)

        stub.text = "".join(lines).rstrip("\n") + "\n"
        return stub

    def render_imports(self, tree: ast.Module) -> List[str]:
        """Return the import statements of a module, in source order.

        The imports are copied rather than computed, because computing the
        set a stub needs means resolving every name in every annotation, and
        copying is both correct and shorter. An import the stub does not use
        is harmless.

        Args:
            tree: The parsed module.

        Returns:
            The rendered import statements, one per line.
        """
        rendered: List[str] = []
        for node in tree.body:
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                statement = unparse(node)
                # The future import is meaningless in a stub, where the
                # deferred evaluation of annotations is already the rule.
                if "__future__" in statement:
                    continue
                rendered.append(statement + "\n")
        return rendered

    def render_exports(self, tree: ast.Module) -> List[str]:
        """Return the ``__all__`` declaration of a module, if it has one.

        The declaration is carried into the stub because it is part of the
        interface: it decides what a wildcard import brings in and what a
        checker treats as public.

        Args:
            tree: The parsed module.

        Returns:
            The rendered declaration, or an empty list.
        """
        for node in tree.body:
            if not isinstance(node, ast.Assign):
                continue
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    return [f"__all__ = {unparse(node.value)}\n"]
        return []

    # -- definitions ------------------------------------------------------

    def render_body(self, tree: ast.Module, path: str, stub: ModuleStub) -> List[str]:
        """Return the rendered definitions of a module.

        Args:
            tree: The parsed module.
            path: The file being rendered, for the findings.
            stub: The stub being built, whose findings this appends to.

        Returns:
            The rendered definitions, separated by blank lines.
        """
        pieces: List[str] = []
        for node in tree.body:
            if isinstance(node, ast.ClassDef):
                if is_private(node.name) and not self.include_private:
                    continue
                pieces.append(self.render_class(node, path, stub))
                stub.emitted += 1
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if is_private(node.name) and not self.include_private:
                    continue
                pieces.append(
                    self.render_function(node, path, stub, indent="", in_class=False)
                )
                stub.emitted += 1
            elif isinstance(node, ast.AnnAssign):
                rendered = self.render_annotated_assignment(node, indent="")
                if rendered:
                    pieces.append(rendered)
                    stub.emitted += 1

        return ["\n".join(pieces)] if pieces else []

    def render_class(self, node: ast.ClassDef, path: str, stub: ModuleStub) -> str:
        """Return the rendered form of one class.

        Args:
            node: The class definition.
            path: The file it is in, for the findings.
            stub: The stub being built.

        Returns:
            The rendered class, including its members.
        """
        lines: List[str] = []
        for decorator in decorator_names(node):
            lines.append(f"@{decorator}")

        bases = [unparse(base) for base in node.bases]
        bases += [
            f"{keyword.arg}={unparse(keyword.value)}" for keyword in node.keywords
        ]
        header = f"class {node.name}"
        if bases:
            header += "(" + ", ".join(bases) + ")"
        lines.append(header + ":")

        members: List[str] = []
        for member in node.body:
            if isinstance(member, ast.AnnAssign):
                rendered = self.render_annotated_assignment(member, indent="    ")
                if rendered:
                    members.append(rendered)
            elif isinstance(member, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if is_private(member.name) and not self.include_private:
                    continue
                members.append(
                    self.render_function(
                        member,
                        path,
                        stub,
                        indent="    ",
                        in_class=True,
                        owner=node.name,
                    )
                )
            elif isinstance(member, ast.ClassDef):
                if is_private(member.name) and not self.include_private:
                    continue
                nested = self.render_class(member, path, stub)
                members.append("\n".join(f"    {line}" for line in nested.splitlines()))

        if not members:
            # A class with no emitted member still needs a body, and the
            # ellipsis is the form a stub uses for one.
            members.append("    ...")

        lines.append("\n".join(members))
        return "\n".join(lines) + "\n"

    def render_function(
        self,
        node: ast.AST,
        path: str,
        stub: ModuleStub,
        indent: str,
        in_class: bool,
        owner: str = "",
    ) -> str:
        """Return the rendered form of one function or method.

        Args:
            node: The function definition.
            path: The file it is in, for the findings.
            stub: The stub being built, whose findings this appends to.
            indent: The leading whitespace for the rendered lines.
            in_class: Whether it is a method.
            owner: The class name, used to qualify a finding.

        Returns:
            The rendered definition, with an ellipsis body.
        """
        qualified = f"{owner}.{node.name}" if owner else node.name
        decorators = decorator_names(node)

        # An overload declares a signature rather than implementing one, so
        # the implementation it belongs to is checked and it is not.
        if "typing.overload" not in decorators and "overload" not in decorators:
            stub.findings.extend(annotation_findings(node, qualified, path, in_class))

        lines: List[str] = []
        for decorator in decorators:
            lines.append(f"{indent}@{decorator}")

        prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
        returns = unparse(node.returns)
        suffix = f" -> {returns}" if returns else ""
        lines.append(
            f"{indent}{prefix} {node.name}({render_signature(node)}){suffix}: ..."
        )
        return "\n".join(lines) + "\n"

    def render_annotated_assignment(self, node: ast.AnnAssign, indent: str) -> str:
        """Return the rendered form of one annotated assignment.

        The value is dropped and replaced by an ellipsis, except for a type
        alias, where the value is the whole point of the declaration.

        Args:
            node: The annotated assignment.
            indent: The leading whitespace.

        Returns:
            The rendered declaration, or the empty string when it is private
            and private names are not being emitted.
        """
        if not isinstance(node.target, ast.Name):
            return ""
        name = node.target.id
        if is_private(name) and not self.include_private:
            return ""

        annotation = unparse(node.annotation)
        if annotation in {"TypeAlias", "typing.TypeAlias"} and node.value is not None:
            return f"{indent}{name}: {annotation} = {unparse(node.value)}\n"
        return f"{indent}{name}: {annotation}\n"


# ---------------------------------------------------------------------------
# Walking the package
# ---------------------------------------------------------------------------


def source_files() -> List[pathlib.Path]:
    """Return the modules to generate stubs for, in a stable order.

    Returns:
        Every Python file under the package, sorted, with the caches left
        out. A file of zero length is included: it is a placeholder for a
        package that is not written yet, and a stub tree that keeps its
        shape is easier to compare against a later one.
    """
    return sorted(
        path for path in PACKAGE_ROOT.rglob("*.py") if "__pycache__" not in path.parts
    )


def generate_all(include_private: bool) -> List[ModuleStub]:
    """Return the stubs for every module in the package.

    Args:
        include_private: Whether to emit private names.

    Returns:
        One stub per module, in file order.
    """
    generator = StubGenerator(include_private=include_private)
    stubs: List[ModuleStub] = []
    for path in source_files():
        try:
            stubs.append(generator.generate(path))
        except SyntaxError as error:
            print(f"error: {path}: {error}", file=sys.stderr)
            raise SystemExit(1) from error
    return stubs


def write_all(stubs: Iterable[ModuleStub], output: pathlib.Path) -> int:
    """Write a stub tree, and the marker that says it is typed.

    The tree mirrors the package layout, so the output directory can be put
    on the path of a checker that wants stubs and nothing else.

    Args:
        stubs: The stubs to write.
        output: The directory to write them under.

    Returns:
        How many files were written, including the marker.
    """
    written = 0
    for stub in stubs:
        destination = output / stub.target
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(stub.text, encoding="utf-8")
        written += 1

    marker = output / "discretus" / "py.typed"
    marker.parent.mkdir(parents=True, exist_ok=True)
    marker.write_text("", encoding="utf-8")
    return written + 1


def collect_findings(stubs: Iterable[ModuleStub]) -> List[Finding]:
    """Return every finding from a set of stubs, in file and line order.

    Args:
        stubs: The stubs to read the findings from.

    Returns:
        The findings, sorted so that the report reads like the source.
    """
    findings: List[Finding] = []
    for stub in stubs:
        findings.extend(stub.findings)
    return sorted(findings, key=lambda finding: (finding.path, finding.line))


# ---------------------------------------------------------------------------
# The stub generator of the type checker
# ---------------------------------------------------------------------------


def run_stubgen(output: pathlib.Path) -> int:
    """Delegate the generation to the stub generator of the type checker.

    Running both and comparing is the point: two independent renderings of
    the same signatures that disagree mean one of them is wrong. The other
    tool imports what it can and parses what it cannot, so it sees defaults
    and aliases differently, and a difference is usually informative rather
    than a defect.

    Args:
        output: The directory to write under.

    Returns:
        A process exit status.
    """
    if shutil.which("stubgen") is None:
        print("error: stubgen is not installed; it comes with mypy", file=sys.stderr)
        print('  python3 -m pip install -e ".[dev]"', file=sys.stderr)
        return 2

    output.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [
            "stubgen",
            "--include-docstrings",
            "--output",
            str(output),
            str(PACKAGE_ROOT.relative_to(REPOSITORY_ROOT)),
        ],
        cwd=REPOSITORY_ROOT,
        check=False,
    )
    return result.returncode


# ---------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------


def compare(
    stubs: Sequence[ModuleStub], output: pathlib.Path
) -> Tuple[List[str], List[str], List[str]]:
    """Compare freshly generated stubs against a previously written tree.

    Args:
        stubs: The freshly generated stubs.
        output: The directory holding the previous tree.

    Returns:
        The stubs that are new, the ones that differ, and the files in the
        tree that no source produces any more.
    """
    fresh: Dict[pathlib.Path, str] = {stub.target: stub.text for stub in stubs}

    added: List[str] = []
    changed: List[str] = []
    for target, text in sorted(fresh.items()):
        existing = output / target
        if not existing.exists():
            added.append(str(target))
        elif existing.read_text(encoding="utf-8") != text:
            changed.append(str(target))

    removed: List[str] = []
    if output.exists():
        for path in sorted(output.rglob("*.pyi")):
            if path.relative_to(output) not in fresh:
                removed.append(str(path.relative_to(output)))

    return added, changed, removed


# ---------------------------------------------------------------------------
# Command line
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    """Return the command line parser.

    Returns:
        The parser. The modes are mutually exclusive, because each one has a
        different notion of what success means.
    """
    parser = argparse.ArgumentParser(
        prog="scripts/generate_stubs.py",
        description=(
            "Generate type stubs for the library from its source, and "
            "report the annotations that are missing."
        ),
        epilog=(
            "The library is annotated inline and ships a py.typed marker, "
            "so the stubs are a convenience for tooling that cannot read "
            "inline annotations, and the audit is the part worth running."
        ),
    )
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument(
        "--check",
        action="store_true",
        help="report the missing annotations and write nothing",
    )
    modes.add_argument(
        "--diff",
        action="store_true",
        help="compare against the written tree and write nothing",
    )
    modes.add_argument(
        "--print",
        dest="print_module",
        metavar="MODULE",
        help="print the stub for one module, by import path or file path",
    )
    parser.add_argument(
        "--output",
        metavar="DIRECTORY",
        default=str(DEFAULT_OUTPUT.relative_to(REPOSITORY_ROOT)),
        help="where to write the stub tree, default build/stubs",
    )
    parser.add_argument(
        "--include-private",
        action="store_true",
        help="emit names with a leading underscore as well",
    )
    parser.add_argument(
        "--use-stubgen",
        action="store_true",
        help="delegate to the stub generator that comes with mypy",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="a missing annotation fails the run even outside --check",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="print only what went wrong",
    )
    return parser


def resolve_module(name: str) -> pathlib.Path:
    """Return the source file a module argument denotes.

    Both forms are accepted, because both are natural: an import path is
    what a contributor reads in a traceback, and a file path is what an
    editor offers to copy.

    Args:
        name: An import path such as ``discretus.core.element``, or a file
            path such as ``discretus/core/element.py``.

    Returns:
        The source file.

    Raises:
        SystemExit: If no such module exists.
    """
    candidate = pathlib.Path(name)
    if candidate.suffix == ".py":
        resolved = (REPOSITORY_ROOT / candidate).resolve()
        if resolved.exists():
            return resolved

    parts = name.split(".")
    module = REPOSITORY_ROOT / pathlib.Path(*parts).with_suffix(".py")
    if module.exists():
        return module
    package = REPOSITORY_ROOT / pathlib.Path(*parts) / "__init__.py"
    if package.exists():
        return package

    print(f"error: no module named {name}", file=sys.stderr)
    raise SystemExit(2)


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


def report_findings(findings: Sequence[Finding]) -> None:
    """Print the findings, grouped so that the report reads like the source.

    Args:
        findings: The findings to print.
    """
    if not findings:
        print("every public signature is fully annotated")
        return

    label = "annotation is" if len(findings) == 1 else "annotations are"
    print(f"{len(findings)} {label} missing:")
    for finding in findings:
        print(f"  {finding.render()}")
    print()
    print("A typed package that omits an annotation is worse than an")
    print("untyped one, because a checker reports nothing and a reader")
    print("assumes the signature was checked.")


def report_written(
    stubs: Sequence[ModuleStub], output: pathlib.Path, written: int
) -> None:
    """Print what the generation produced.

    Args:
        stubs: The stubs that were written.
        output: Where they went.
        written: How many files were written.
    """
    definitions = sum(stub.emitted for stub in stubs)
    print(f"wrote {written} files to {output}")
    print(f"{len(stubs)} modules, {definitions} public definitions")
    print()
    print("Point a checker that wants stubs at the tree:")
    print(f"  MYPYPATH={output} mypy --no-site-packages your_code.py")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Generate the stubs, or audit the annotations behind them.

    Args:
        argv: The command line arguments, defaulting to the real ones.

    Returns:
        A process exit status.
    """
    arguments = build_parser().parse_args(argv)
    output = (REPOSITORY_ROOT / arguments.output).resolve()

    if not PACKAGE_ROOT.is_dir():
        print(f"error: {PACKAGE_ROOT} is not a directory", file=sys.stderr)
        return 2

    if arguments.use_stubgen:
        return run_stubgen(output)

    if arguments.print_module is not None:
        stub = StubGenerator(include_private=arguments.include_private).generate(
            resolve_module(arguments.print_module)
        )
        sys.stdout.write(stub.text)
        if stub.findings and not arguments.quiet:
            print(file=sys.stderr)
            for finding in stub.findings:
                print(f"  {finding.render()}", file=sys.stderr)
        return 1 if stub.findings and arguments.strict else 0

    stubs = generate_all(include_private=arguments.include_private)
    findings = collect_findings(stubs)

    if arguments.check:
        report_findings(findings)
        return 1 if findings else 0

    if arguments.diff:
        added, changed, removed = compare(stubs, output)
        if not (added or changed or removed):
            print(f"the tree in {output} is up to date")
            return 0
        for label, names in (
            ("new", added),
            ("different", changed),
            ("no longer produced", removed),
        ):
            if names:
                print(f"{len(names)} {label}:")
                for name in names:
                    print(f"  {name}")
        print()
        print("Regenerate with: scripts/generate_stubs.py")
        return 1

    written = write_all(stubs, output)
    if not arguments.quiet:
        report_written(stubs, output, written)
        print()
        report_findings(findings)

    return 1 if findings and arguments.strict else 0


if __name__ == "__main__":
    raise SystemExit(main())
